import './globals.scss'
import type { Metadata } from 'next'
import { Inter, Roboto_Flex, Roboto_Slab } from 'next/font/google'
import styles from './layout.module.css'
//import NavBar from './components/navbar/navbar'
import { UserThemeProvider } from '@/lib/context'
import dynamic from 'next/dynamic'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'

const inter = Inter({ subsets: ['latin'] })

const robotoFlex = Roboto_Slab({ subsets: ['latin'], display: 'swap' })

export const metadata: Metadata = {
    title: 'Drizzle',
    description: 'Generated by create next app',
}

const NavBar = dynamic(() => import('./components/navbar/navbar'), {
    ssr: false,
})

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={robotoFlex.className}>
            <body className={styles.body}>
                <AppRouterCacheProvider>
                    <UserThemeProvider>
                        <NavBar />
                        <main className={styles.main}>{children}</main>
                    </UserThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    )
}
